# docker pull pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
# FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime

# docker pull pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime


# libGL.so.1: cannot open shared object file: No such file or directory
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    wget \
    curl \
    bzip2


# Create a non-root user with a home directory and bash shell
RUN useradd --create-home --shell /bin/bash awesomeuser

# Set the working directory to the new user's home
WORKDIR /home/awesomeuser


# Copying application files, adjust ownership
# WORKDIR /code
# RUN mv /code ControlNet
# RUN chown -R awesomeuser:awesomeuser ControlNet
USER awesomeuser
RUN mkdir /home/awesomeuser/cc_pipeline
RUN mkdir /home/awesomeuser/cc_pipeline/models/ && curl -L https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_canny.pth -o /home/awesomeuser/cc_pipeline/models/control_sd15_canny.pth
COPY . /home/awesomeuser/cc_pipeline

WORKDIR /home/awesomeuser/cc_pipeline
# The following creates the environment "cc_pipeline"
RUN conda env create -f environment.yml
# before doing the following, you need have to have generated the whl:
# tox -e build
RUN conda run -n cc_pipeline /bin/bash -c "pip install /home/awesomeuser/cc_pipeline/dist/*.whl"

USER root
# ImportError: libSM.so.6: cannot open shared object file: No such file or directory
# ImportError: libXrender.so.1: cannot open shared object file: No such file or directory
RUN apt-get update && apt-get install -y libsm6 libxrender-dev
USER awesomeuser


# docker build -t cc_controlnet_cuda -f Dockerfile_environment .
